<?php

/**
 * @file
 * Functions to add hooks for this module.
 */

/**
 * Implements hook_preprocess_HOOK() for block templates.
 */
function dp_world_news_preprocess_block(&$variables) {
  if ($variables['base_plugin_id'] === 'dp_world_news') {
    $variables['articles'] = [];
    if ($variables['content']['articles']['#markup']) {
      $variables['articles'] = $variables['content']['articles']['#markup'];
    }
  }
}
