dp_world_news.settings:
  type: config_object
  label: 'World News settings'
  mapping:
    news_api_api_key:
      type: string
    news_api:
      type: mapping
      mapping:
        api_key:
          type: string
          label: 'API Key'
    news_data_api_key:
      type: string
    news_data:
      type: mapping
      mapping:
        api_key:
          type: string
          label: 'API Key'
